version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

conda:
  environment: docs/environment.yml

build:
  image: latest

python:
  version: 3.8
  install:
    - method: pip
      path: .