version: 2

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: docs/environment.yml

formats:
  - pdf
  - epub

build:
  image: latest

python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt